In [1]:
from tweepy.streaming import StreamListener
from tweepy import OAuthHandler
from tweepy import Stream
import pandas as pd
import json
# import dataset
import credentials
import sqlite3
import nltk
from nltk.tokenize import RegexpTokenizer
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
import pickle
from Naive_bayes_model import *
import xgboost as xgb

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


In [2]:
f = open('nb1.pickle', 'rb')
NBayesClassifier = pickle.load(f)
f.close()

In [3]:
f1 = open('xgb', 'rb')
XGBClassifier = pickle.load(f1)
f1.close()

In [4]:
conn = sqlite3.connect('tweet2.db')
c = conn.cursor()

In [5]:
def pred(data):
    
    tweetProcessor = PreProcessTweets()
    preprocessedTrainingSet = tweetProcessor.processTweets(data)
    
    word_features = buildVocabulary(preprocessedTrainingSet)
#     print("\n",word_features,"\n")
#     buildVocabulary(preprocessedTrainingSet)
    trainingFeatures = nltk.classify.apply_features(extract_features, preprocessedTrainingSet)
    
    print(preprocessedTrainingSet[0][0])
    
    NB = NBayesClassifier.classify(extract_features(preprocessedTrainingSet[0][0],word_features))
    
    return NB
    

In [6]:

def attributeselection(tweet,query_word):
    attr= []

    #text = "Alleged East Bay serial arsonist arrested #SanFrancisco - http://t.co/ojuHfkHVb2"
    tweet = tweet.lower() # convert text to lower-case
    tweet = re.sub('((www\.[^\s]+)|(https?://[^\s]+))', 'URL', tweet) # remove URLs
    tweet = re.sub('@[^\s]+', 'AT_USER', tweet) # remove username
    tweet = re.sub(r'#([^\s]+)', r'\1', tweet) # remove the # in #hashtag
    tweet = re.sub(r'\\s+',r' ', tweet, flags=re.I)
    tweet = re.sub("([^\x00-\x7F])+"," ",tweet) #remove all non-english characters
    tweet = re.sub(r"\s+"," ", tweet, flags = re.I) #remove multiple spaces
    text = tweet
    text = nltk.word_tokenize(text)
    poslist = nltk.pos_tag(text)
#     print(poslist)

    verblist = []
    for i in range(len(poslist)):
        if poslist[i][1].startswith('V'):
            verblist.append(poslist[i])
    
    word_count = len(poslist)
#     print(word_count)

    if len(verblist) == 0:
        l = (query_word,'VB')
        verblist.append(l)
    
#     print(verblist,"\n")
    verb_count = len(verblist)
#     print(verb_count)

   # query_word = 'arson'

    words_before = words_after = 0
    for i in range(len(poslist)):
        if poslist[i][0].startswith(query_word):
            words_before = i

    words_after = word_count - words_before - 1

#     print(words_before)
#     print(words_after)
    verbs = []    
    attr.append(word_count)
#     for i in verblist:
#         print(i[0])
#         verbs.append(i[0])
#     attr.append(verbs)
    attr.append(verb_count)
    attr.append(words_before + 1)
#     attr_query_word.append(query_word)
    attr.append(words_before)
    attr.append(words_after)
    
    
        
    column_names = ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
    print(attr,column_names)
    df = pd.DataFrame([attr], columns=column_names)
    arr_x=df.to_numpy(dtype=object)
    print(arr_x,arr_x.shape)
    y_pred = XGBClassifier.predict(arr_x)
    print("PRIORITY: ",y_pred)
    
    

In [7]:
class TwitterStreamer():
    
    def stream_tweets(self, fetched_tweets_filename, hash_tag_list):
        listener = StdOutListener(fetched_tweets_filename)
        auth = OAuthHandler(credentials.CONSUMER_KEY, credentials.CONSUMER_SECRET)
        auth.set_access_token(credentials.ACCESS_TOKEN, credentials.ACCESS_TOKEN_SECRET)
        
        stream = Stream(auth, listener,tweet_mode='extended')
        
        stream.filter(languages=["en"],track=['coronavirus'])
        
 
class StdOutListener(StreamListener):
    
    def on_status(self, status):
        print(status.text)

    def on_error(self, status):
        print(status)

    def on_data(self, data):
        all_data             = json.loads(data)
        created_at           = all_data['created_at']
        favorite_count       = all_data['favorite_count']
        favorited            = all_data['favorited']
        filter_level         = all_data['filter_level']
        lang                 = all_data['lang']
        retweet_count        = all_data['retweet_count']
        retweeted            = all_data['retweeted']
        source               = all_data['source']
        text                 = all_data['text']
        truncated            = all_data['truncated']
        user_created_at      = all_data['user']['created_at']
        user_followers_count = all_data['user']['followers_count']
        user_location        = all_data['user']['location']
        user_lang            = all_data['user']['lang']
        user_name            = all_data['user']['name']
        user_screen_name     = all_data['user']['screen_name']
        user_time_zone       = all_data['user']['time_zone']
        user_utc_offset      = all_data['user']['utc_offset']
        user_friends_count   = all_data['user']['friends_count']
        geo_enabled          = all_data['user']['geo_enabled']  
        coordinates          = all_data['coordinates']
        geo                  = all_data['geo']
        place                = all_data['place']
        if place is not None:
            place_name       = all_data['place']['name']
        else:
            place_name       = all_data['place']

        print("Tweet: "+text+"\n")
        
        data = [{'text': text,'Classfication': ''}]
        
        info = pred(data)
        
        if info == 'Relevant' or info == 1 or info == '1':
            attributeselection(text,'coronavirus')
            
        print("\n Class: "+info+"\n")
                         
        c.execute('''INSERT INTO tweets 
        (created_at, favorite_count, favorited, filter_level, lang, 
                         retweet_count, retweeted, source, text, truncated, user_created_at,  
                         user_followers_count, user_location, user_lang, user_name, 
                         user_screen_name, user_time_zone, user_friends_count,geo_enabled,coordinates,geo,place_name ) 
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)''', 
            (created_at, favorite_count, favorited, filter_level, lang, retweet_count, 
                         retweeted, source, text, truncated, user_created_at, 
                         user_followers_count, user_location, user_lang, user_name, 
                         user_screen_name, user_time_zone, user_friends_count,geo_enabled,coordinates,geo,place_name ))
        
        c.execute('''INSERT INTO tweet_class 
        (text, class) 
            VALUES (?,?)''', 
            (text, info))
        
        conn.commit()

In [8]:
if __name__ == '__main__':
    
    hash_tag_list = ['coronavirus']
    fetched_tweets_filename = "tweets.json"
    
    twitter_streamer = TwitterStreamer()
    twitter_streamer.stream_tweets(fetched_tweets_filename, hash_tag_list)

Tweet: RT @ThePlumLineGS: Kellyanne Conway just previewed the Big Lie that Trump will use to salvage reelection amid his coronavirus fiasco.

It r…

['rt', 'kellyanne', 'conway', 'previewed', 'big', 'lie', 'trump', 'use', 'salvage', 'reelection', 'amid', 'coronavirus', 'fiasco', 'r…']
[23, 4, 19, 18, 4] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[23 4 19 18 4]] (1, 5)
PRIORITY:  [0]

 Class: 1



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @ChrisJZullo: @BarackObama Donald Trump knew in January dangers of Coronavirus. Didn’t buy, produce mass tests. Didn’t push social dista…

['rt', 'donald', 'trump', 'knew', 'january', 'dangers', 'coronavirus', '’', 'buy', 'produce', 'mass', 'tests', '’', 'push', 'social', 'dista…']

 Class: 0

Tweet: RT @SAL3977: Please lord have mercy!! 🙏🏼🙏🏼
Field hospital in Central Park ....
#coronavirus #NYC #COVID19 #CentralPark https://t.co/IGTuPAD…

['rt', 'please', 'lord', 'mercy', '🙏🏼🙏🏼', 'field', 'hospital', 'central', 'park', '...', 'coronavirus', 'nyc', 'covid19', 'centralpark']
[20, 3, 16, 15, 4] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[20 3 16 15 4]] (1, 5)
PRIORITY:  [0]

 Class: 1



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @ScramNews: Gove and Hancock said something that was blatantly false.
https://t.co/Lj3wBQJPW9

['rt', 'gove', 'hancock', 'said', 'something', 'blatantly', 'false']

 Class: 0

Tweet: RT @silverncopper: Treasury Secretary Mnuchin says ‘Americans need cash now;’ lawmakers in both parties urge government to send funds to ho…

['rt', 'treasury', 'secretary', 'mnuchin', 'says', '‘', 'americans', 'need', 'cash', '’', 'lawmakers', 'parties', 'urge', 'government', 'send', 'funds', 'ho…']
[22, 5, 1, 0, 21] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[22 5 1 0 21]] (1, 5)
PRIORITY:  [0]

 Class: 1



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @pieter3800: Do they really have to remove a cheek?

['rt', 'really', 'remove', 'cheek']

 Class: 0

Tweet: Ain't going out cuz yall got the cooties. Catch me like.. 
#SocialDistancing #COVID19 #coronavirus https://t.co/M8XyVsQ2ig

['ai', "n't", 'going', 'cuz', 'yall', 'got', 'cooties', 'catch', 'like..', 'socialdistancing', 'covid19', 'coronavirus']

 Class: 0

Tweet: Truth on the ground...vs. trump truth https://t.co/XcrTPFg9vP

['truth', 'ground', '...', 'vs.', 'trump', 'truth']

 Class: 0

Tweet: RT @JRFBarros: What can EU learn from Swiss and Scandinavian carbon #tax policies? Interesting read by @epicenterEU. Now more than ever we…

['rt', 'eu', 'learn', 'swiss', 'scandinavian', 'carbon', 'tax', 'policies', 'interesting', 'read', 'ever', 'we…']

 Class: 0

Tweet: RT @NorbertElekes: Bad news from the UK:

- Record number of new cases
- Record number of new deaths
- Fatality rate at all-time high

['rt', 'bad', 'news', 'uk', 'record', 'number', 'new', 'cases', 'record', '

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @morganfmckay: NUMBERS FOR TUESDAY: 
Total Coronavirus cases: 75,795
Number of new cases: 9,298
People who have passed away: 1,550 - Thi…

['rt', 'numbers', 'tuesday', 'total', 'coronavirus', 'cases', '75,795', 'number', 'new', 'cases', '9,298', 'people', 'passed', 'away', '1,550', 'thi…']
[26, 2, 8, 7, 18] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[26 2 8 7 18]] (1, 5)
PRIORITY:  [0]

 Class: 1

Tweet: RT @NYTHealth: Addiction experts call the coronavirus pandemic an extraordinary relapse trigger. Here are some virtual supports to help peo…

['rt', 'addiction', 'experts', 'call', 'coronavirus', 'pandemic', 'extraordinary', 'relapse', 'trigger', 'virtual', 'supports', 'help', 'peo…']
[21, 5, 7, 6, 14] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[21 5 7 6 14]] (1, 5)
PRIORITY:  [0]

 Class: 1



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @IngrahamAngle: Coming up on the #IngrahamAngle, Stanford's Nobel Prize winner Michael Levitt, on why U.S. coronavirus recovery will be…

['rt', 'coming', 'ingrahamangle', 'stanford', "'s", 'nobel', 'prize', 'winner', 'michael', 'levitt', 'u.s.', 'coronavirus', 'recovery', 'be…']

 Class: 0

Tweet: RT @RexChapman: Coronavirus silver-linings: 

Jack Black is now on Tik Tok... https://t.co/O5ji9L2dgv

['rt', 'coronavirus', 'silver-linings', 'jack', 'black', 'tik', 'tok', '...']

 Class: 0

Tweet: RT @BW: Divorces are spiking in China as couples emerge from their coronavirus quarantines https://t.co/zhBKPtYsfu

['rt', 'divorces', 'spiking', 'china', 'couples', 'emerge', 'coronavirus', 'quarantines']

 Class: 0

Tweet: Oh no.

['oh']

 Class: 0

Tweet: RT @LSEFaithCentre: If you are looking for online resources from a Muslim perspective during these times, look at the Yaqeen Institute's se…

['rt', 'looking', 'online', 'resources', 'muslim', 'perspective', 'times', 'look', 'yaqee

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @mmpadellan: When this is all over, and it WILL be, I will never forgive or forget trump's refusal to take coronavirus seriously.

I won…

['rt', 'never', 'forgive', 'forget', 'trump', "'s", 'refusal', 'take', 'coronavirus', 'seriously', 'won…']

 Class: 0

Tweet: RT @realDonaldTrump: Thank you Mike!

['rt', 'thank', 'mike']

 Class: 0

Tweet: RT @DavidBegnaud: Alabama's 'Last Resort' plan: "...any of a wide range of underlying health conditions – such as metastasized cancer, AIDS…

['rt', 'alabama', "'s", "'last", 'resort', 'plan', '``', '...', 'wide', 'range', 'underlying', 'health', 'conditions', '–', 'metastasized', 'cancer', 'aids…']
[26, 1, 1, 0, 25] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[26 1 1 0 25]] (1, 5)
PRIORITY:  [0]

 Class: 1

Tweet: RT @PrisonPlanet: UK government to release an app which alerts you to people infected with coronavirus nearby.

Tracks your location, pings…

['rt', 'uk', 'government', 'release', 'app', 'al

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @Bee_Bob: From @NYGovCuomo - #coronavirus in Rockland rise to a total of 2,863, up by 352 cases @lohud

['rt', 'coronavirus', 'rockland', 'rise', 'total', '2,863', '352', 'cases']
[20, 1, 6, 5, 14] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[20 1 6 5 14]] (1, 5)
PRIORITY:  [0]

 Class: 1

Tweet: RT @nowthisnews: Rep. @AOC spoke to soccer star @mPinoe about the two crises facing the U.S. as the coronavirus continues to spread https:/…

['rt', 'rep.', 'spoke', 'soccer', 'star', 'two', 'crises', 'facing', 'u.s.', 'coronavirus', 'continues', 'spread', 'https', '/…']
[25, 6, 19, 18, 6] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[25 6 19 18 6]] (1, 5)
PRIORITY:  [0]

 Class: 1



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @permie777: Many more people died today at the hands of the police than died by coronavirus. This fact will not change. Never call the p…

['rt', 'many', 'people', 'died', 'today', 'hands', 'police', 'died', 'coronavirus', 'fact', 'change', 'never', 'call', 'p…']

 Class: 0

Tweet: RT @NightlyPolitics: Reported US coronavirus cases via @CNN:

Four weeks ago: 102
Three weeks ago: 678
Two weeks ago: 4,459
One week ago: 4…

['rt', 'reported', 'us', 'coronavirus', 'cases', 'via', 'four', 'weeks', 'ago', '102', 'three', 'weeks', 'ago', '678', 'two', 'weeks', 'ago', '4,459', 'one', 'week', 'ago', '4…']
[28, 1, 5, 4, 23] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[28 1 5 4 23]] (1, 5)
PRIORITY:  [0]

 Class: 1



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @ReutersIndia: Here are some of the key terms surrounding the new coronavirus explained, as new words and phrases enter the mainstream a…

['rt', 'key', 'terms', 'surrounding', 'new', 'coronavirus', 'explained', 'new', 'words', 'phrases', 'enter', 'mainstream', 'a…']
[24, 4, 13, 12, 11] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[24 4 13 12 11]] (1, 5)
PRIORITY:  [0]

 Class: 1

Tweet: RT @SolomonYue: Sign this petition to hold China accountable for #Wuhan virus damages. https://t.co/8bly5h8fJd

['rt', 'sign', 'petition', 'hold', 'china', 'accountable', 'wuhan', 'virus', 'damages']

 Class: 0

Tweet: RT @justinallen_13: Coronavirus will end soon. In Jesus name.

['rt', 'coronavirus', 'end', 'soon', 'jesus', 'name']

 Class: 0

Tweet: RT @ClarkeMicah: Peter Hitchens @ClarkeMicah versus @PiersMorgan on the coronavirus - the full debate
https://t.co/OqmhKlWtfQ

['rt', 'peter', 'hitchens', 'versus', 'coronavirus', 'full', 'debate']

 Class: 0



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: Unsurprisingly, this @LizNeeley piece is extremely good!!!!  https://t.co/KDzkZfZVHL

['unsurprisingly', 'piece', 'extremely', 'good']
[13, 1, 1, 0, 12] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[13 1 1 0 12]] (1, 5)
PRIORITY:  [0]

 Class: 1

Tweet: COVID19 DECONTAMINATION EXPANDING
#VmAfrica #Covid19SA #CoronaVirus #StayHome #SA

@gpgSocDev 
Covid19 Disaster Man… https://t.co/GDLMcHV64g

['covid19', 'decontamination', 'expanding', 'vmafrica', 'covid19sa', 'coronavirus', 'stayhome', 'sa', 'covid19', 'disaster', 'man…']

 Class: 0



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @jbouie: This isn't a bad news analysis but it is still very weird to read reporters write around the fact that Trump is an adult toddle…

['rt', "n't", 'bad', 'news', 'analysis', 'still', 'weird', 'read', 'reporters', 'write', 'around', 'fact', 'trump', 'adult', 'toddle…']

 Class: 0

Tweet: RT @sandyaschneider: Funny how everybody with a degree is sitting at home right now and the trades are running this entire nation..
#corona…

['rt', 'funny', 'everybody', 'degree', 'sitting', 'home', 'right', 'trades', 'running', 'entire', 'nation..', 'corona…']

 Class: 0

Tweet: RT @ThirdForceNews: More than 20,000 people have signed up to support Scotland through the coronavirus crisis in just 24 hours @scotgov @Vo…

['rt', '20,000', 'people', 'signed', 'support', 'scotland', 'coronavirus', 'crisis', '24', 'hours']
[22, 3, 15, 14, 7] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[22 3 15 14 7]] (1, 5)
PRIORITY:  [0]

 Class: 1

Tweet: Doug says he's ta

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @DavidCornDC: Trump played golf eight times from mid-January to early March, as the #coronavirus crisis deepened. So his attention was h…

['rt', 'trump', 'played', 'golf', 'eight', 'times', 'mid-january', 'early', 'march', 'coronavirus', 'crisis', 'deepened', 'attention', 'h…']
[24, 3, 16, 15, 8] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[24 3 16 15 8]] (1, 5)
PRIORITY:  [0]

 Class: 1

Tweet: RT @TeamPelosi: People across the United States are taking the necessary steps to stay safe and healthy during the #Coronavirus crisis. 

N…

['rt', 'people', 'across', 'united', 'states', 'taking', 'necessary', 'steps', 'stay', 'safe', 'healthy', 'coronavirus', 'crisis', 'n…']
[23, 4, 20, 19, 3] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[23 4 20 19 3]] (1, 5)
PRIORITY:  [0]

 Class: 1



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @rahulroushan: India Today Data Intelligence Unit goes global

['rt', 'india', 'today', 'data', 'intelligence', 'unit', 'goes', 'global']
[9, 1, 1, 0, 8] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[9 1 1 0 8]] (1, 5)
PRIORITY:  [0]

 Class: 1

Tweet: RT @shaunking: I do not care what you think of me when I say this. 

This video of @JoeBiden struggling to answer a simple question about h…

['rt', 'care', 'think', 'say', 'video', 'struggling', 'answer', 'simple', 'question', 'h…']

 Class: 0



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @allafrica: Zimbabweans Enter COVID-19 Lockdown in the Midst of Severe Economic Crisis https://t.co/E3FkjNQuCS #CoronavirusOutbreak #Cor…

['rt', 'zimbabweans', 'enter', 'covid-19', 'lockdown', 'midst', 'severe', 'economic', 'crisis', 'coronavirusoutbreak', 'cor…']
[16, 1, 15, 14, 1] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[16 1 15 14 1]] (1, 5)
PRIORITY:  [0]

 Class: 1

Tweet: RT @cdnwomenfdn: "Women's advocates say they fear a toxic combination of stress, job losses and isolation caused by COVID-19 could lead to…

['rt', '``', 'women', "'s", 'advocates', 'say', 'fear', 'toxic', 'combination', 'stress', 'job', 'losses', 'isolation', 'caused', 'covid-19', 'could', 'lead', 'to…']
[25, 5, 1, 0, 24] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[25 5 1 0 24]] (1, 5)
PRIORITY:  [0]

 Class: 1



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: Points for creativity! 🤣🤣🤣https://t.co/1Cm3FIFuAw

['points', 'creativity', '🤣🤣🤣URL']

 Class: 0

Tweet: RT @AdamWagner1: I have recorded an episode of @BHumanPodcast with @davidallengreen taking a detailed look at the Coronavirus Regulations a…

['rt', 'recorded', 'episode', 'taking', 'detailed', 'look', 'coronavirus', 'regulations', 'a…']

 Class: 0

Tweet: RT @Thursfields: Furlough leave – the government releases further guidance - https://t.co/VThgvm5NqD https://t.co/yg4uUlA1zU

['rt', 'furlough', 'leave', '–', 'government', 'releases', 'guidance']

 Class: 0

Tweet: RT @TeaPainUSA: Lyin' about the dead?  Can MAGA get any sicker?  

https://t.co/IW1ungQh2X

['rt', 'lyin', 'dead', 'maga', 'get', 'sicker']
[15, 2, 1, 0, 14] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[15 2 1 0 14]] (1, 5)
PRIORITY:  [0]

 Class: 1



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: Great tips for keeping your devices a bit safer in the age of #CoronaVirus #CoronaVirusLockdown, from #@Fox29Philly https://t.co/B86QqNAyeL

['great', 'tips', 'keeping', 'devices', 'bit', 'safer', 'age', 'coronavirus', 'coronaviruslockdown']

 Class: 0



KeyError: 'created_at'