In [9]:
from tweepy.streaming import StreamListener
from tweepy import OAuthHandler
from tweepy import Stream
import pandas as pd
import json
# import dataset
import credentials
import sqlite3
import nltk
from nltk.tokenize import RegexpTokenizer
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
import pickle
from Naive_bayes_model import *
import xgboost as xgb

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


In [10]:
f = open('nb2.pickle', 'rb')
NBayesClassifier = pickle.load(f)
f.close()

In [11]:
f1 = open('xgb', 'rb')
XGBClassifier = pickle.load(f1)
f1.close()

In [12]:
conn = sqlite3.connect('tweet2.db')
c = conn.cursor()

In [13]:
def pred(data):
    
    tweetProcessor = PreProcessTweets()
    preprocessedTrainingSet = tweetProcessor.processTweets(data)
    
    word_features = buildVocabulary(preprocessedTrainingSet)
#     print("\n",word_features,"\n")
#     buildVocabulary(preprocessedTrainingSet)
    trainingFeatures = nltk.classify.apply_features(extract_features, preprocessedTrainingSet)
    
    print(preprocessedTrainingSet[0][0])
    
    NB = NBayesClassifier.classify(extract_features(preprocessedTrainingSet[0][0],word_features))
    
    return NB
    

In [14]:

def attributeselection(tweet,query_word):
    attr= []

    #text = "Alleged East Bay serial arsonist arrested #SanFrancisco - http://t.co/ojuHfkHVb2"
    tweet = tweet.lower() # convert text to lower-case
    tweet = re.sub('((www\.[^\s]+)|(https?://[^\s]+))', 'URL', tweet) # remove URLs
    tweet = re.sub('@[^\s]+', 'AT_USER', tweet) # remove username
    tweet = re.sub(r'#([^\s]+)', r'\1', tweet) # remove the # in #hashtag
    tweet = re.sub(r'\\s+',r' ', tweet, flags=re.I)
    tweet = re.sub("([^\x00-\x7F])+"," ",tweet) #remove all non-english characters
    tweet = re.sub(r"\s+"," ", tweet, flags = re.I) #remove multiple spaces
    text = tweet
    text = nltk.word_tokenize(text)
    poslist = nltk.pos_tag(text)
#     print(poslist)

    verblist = []
    for i in range(len(poslist)):
        if poslist[i][1].startswith('V'):
            verblist.append(poslist[i])
    
    word_count = len(poslist)
#     print(word_count)

    if len(verblist) == 0:
        l = (query_word,'VB')
        verblist.append(l)
    
#     print(verblist,"\n")
    verb_count = len(verblist)
#     print(verb_count)

   # query_word = 'arson'

    words_before = words_after = 0
    for i in range(len(poslist)):
        if poslist[i][0].startswith(query_word):
            words_before = i

    words_after = word_count - words_before - 1

#     print(words_before)
#     print(words_after)
    verbs = []    
    attr.append(word_count)
#     for i in verblist:
#         print(i[0])
#         verbs.append(i[0])
#     attr.append(verbs)
    attr.append(verb_count)
    attr.append(words_before + 1)
#     attr_query_word.append(query_word)
    attr.append(words_before)
    attr.append(words_after)
    
    
        
    column_names = ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
    print(attr,column_names)
    df = pd.DataFrame([attr], columns=column_names)
    arr_x=df.to_numpy(dtype=object)
    print(arr_x,arr_x.shape)
    y_pred = XGBClassifier.predict(arr_x)
    print("PRIORITY: ",y_pred)
    
    

In [15]:
class TwitterStreamer():
    
    def stream_tweets(self, fetched_tweets_filename, hash_tag_list):
        listener = StdOutListener(fetched_tweets_filename)
        auth = OAuthHandler(credentials.CONSUMER_KEY, credentials.CONSUMER_SECRET)
        auth.set_access_token(credentials.ACCESS_TOKEN, credentials.ACCESS_TOKEN_SECRET)
        
        stream = Stream(auth, listener,tweet_mode='extended')
        
        stream.filter(languages=["en"],track=['coronavirus'])
        
 
class StdOutListener(StreamListener):
    
    def on_status(self, status):
        print(status.text)

    def on_error(self, status):
        print(status)

    def on_data(self, data):
        all_data             = json.loads(data)
        created_at           = all_data['created_at']
        favorite_count       = all_data['favorite_count']
        favorited            = all_data['favorited']
        filter_level         = all_data['filter_level']
        lang                 = all_data['lang']
        retweet_count        = all_data['retweet_count']
        retweeted            = all_data['retweeted']
        source               = all_data['source']
        text                 = all_data['text']
        truncated            = all_data['truncated']
        user_created_at      = all_data['user']['created_at']
        user_followers_count = all_data['user']['followers_count']
        user_location        = all_data['user']['location']
        user_lang            = all_data['user']['lang']
        user_name            = all_data['user']['name']
        user_screen_name     = all_data['user']['screen_name']
        user_time_zone       = all_data['user']['time_zone']
        user_utc_offset      = all_data['user']['utc_offset']
        user_friends_count   = all_data['user']['friends_count']
        geo_enabled          = all_data['user']['geo_enabled']  
        coordinates          = all_data['coordinates']
        geo                  = all_data['geo']
        place                = all_data['place']
        if place is not None:
            place_name       = all_data['place']['name']
        else:
            place_name       = all_data['place']

        print("Tweet: "+text+"\n")
        
        data = [{'text': text,'Classfication': ''}]
        
        info = pred(data)
        
        if info == 'Relevant' or info == 1 or info == '1':
            attributeselection(text,'coronavirus')
            
        print("\n Class: "+info+"\n")
                         
        c.execute('''INSERT INTO tweets 
        (created_at, favorite_count, favorited, filter_level, lang, 
                         retweet_count, retweeted, source, text, truncated, user_created_at,  
                         user_followers_count, user_location, user_lang, user_name, 
                         user_screen_name, user_time_zone, user_friends_count,geo_enabled,coordinates,geo,place_name ) 
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)''', 
            (created_at, favorite_count, favorited, filter_level, lang, retweet_count, 
                         retweeted, source, text, truncated, user_created_at, 
                         user_followers_count, user_location, user_lang, user_name, 
                         user_screen_name, user_time_zone, user_friends_count,geo_enabled,coordinates,geo,place_name ))
        
        c.execute('''INSERT INTO tweet_class 
        (text, class) 
            VALUES (?,?)''', 
            (text, info))
        
        conn.commit()

In [16]:
if __name__ == '__main__':
    
    hash_tag_list = ['coronavirus']
    fetched_tweets_filename = "tweets.json"
    
    twitter_streamer = TwitterStreamer()
    twitter_streamer.stream_tweets(fetched_tweets_filename, hash_tag_list)

Tweet: RT @CREWcrew: We need to talk about Jared Kushner's coronavirus task force, and how it appears to be breaking not one, but two laws by oper…

['rt', 'need', 'talk', 'jared', 'kushner', "'s", 'coronavirus', 'task', 'force', 'appears', 'breaking', 'one', 'two', 'laws', 'oper…']

 Class: Not Relevant

Tweet: RT @BadFoxGraphics: "A team of Oscar engineers, project managers, and executives spent about five days building a stand-alone website at th…

['rt', '``', 'team', 'oscar', 'engineers', 'project', 'managers', 'executives', 'spent', 'five', 'days', 'building', 'stand-alone', 'website', 'th…']
[24, 3, 1, 0, 23] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[24 3 1 0 23]] (1, 5)
PRIORITY:  [0]

 Class: Relevant

Tweet: RT @AaronFullerton: Your coronavirus/April Fool's plan is a bad idea. Trust me.

['rt', 'coronavirus/april', 'fool', "'s", 'plan', 'bad', 'idea', 'trust']

 Class: Not Relevant



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @Nigensei: Empty hotels all over the city of Las Vegas and they’re putting the homeless in a fucking parking lot.

['rt', 'empty', 'hotels', 'city', 'las', 'vegas', '’', 'putting', 'homeless', 'fucking', 'parking', 'lot']

 Class: Not Relevant

Tweet: RT @paperdragun: she prolly don’t even know about the coronavirus https://t.co/E7PU5BY8yZ

['rt', 'prolly', '’', 'even', 'know', 'coronavirus']

 Class: Not Relevant

Tweet: RT @carolecadwalla: ‘Now that we've missed the opportunity for early testing, is it too late for testing to make a difference?’

‘Absolutel…

['rt', '‘', "'ve", 'missed', 'opportunity', 'early', 'testing', 'late', 'testing', 'make', 'difference', '’', '‘', 'absolutel…']
[25, 5, 1, 0, 24] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[25 5 1 0 24]] (1, 5)
PRIORITY:  [0]

 Class: Relevant



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: Go easy on yourself. As a long-time #RemoteWorker, my focus isn't where it was before #Coronavirus. You're not the… https://t.co/pZdXZAM7XV

['go', 'easy', 'long-time', 'remoteworker', 'focus', "n't", 'coronavirus', "'re", 'the…']

 Class: Not Relevant

Tweet: RT @charliekirk11: Why is it that—because of Coronavirus—pastors are being arrested for holding church services but child rapists are being…

['rt', 'that—because', 'coronavirus—pastors', 'arrested', 'holding', 'church', 'services', 'child', 'rapists', 'being…']
[22, 7, 9, 8, 13] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[22 7 9 8 13]] (1, 5)
PRIORITY:  [0]

 Class: Relevant



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @associatesmind: There is being an asshole in a crisis, and then there is President-of-the-HOA-during-a-crisis level of asshole. 

#Coro…

['rt', 'asshole', 'crisis', 'president-of-the-hoa-during-a-crisis', 'level', 'asshole', 'coro…']

 Class: Not Relevant

Tweet: RT @funder: Moscow Mitch McConnell says everyone was distracted with impeachment and that’s why Trump failed with his coronavirus response.…

['rt', 'moscow', 'mitch', 'mcconnell', 'says', 'everyone', 'distracted', 'impeachment', '’', 'trump', 'failed', 'coronavirus', 'response.…']
[22, 4, 20, 19, 2] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[22 4 20 19 2]] (1, 5)
PRIORITY:  [0]

 Class: Relevant



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: Those ones the travel?

['ones', 'travel']

 Class: Not Relevant

Tweet: RT @HenryMakow: https://t.co/mkkntLtzzD

Belarus President Lukashenko Takes One Look at Coronavirus and Spits in Its Eye. Won’t Rescind Fre…

['rt', 'belarus', 'president', 'lukashenko', 'takes', 'one', 'look', 'coronavirus', 'spits', 'eye', '’', 'rescind', 'fre…']
[21, 3, 11, 10, 10] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[21 3 11 10 10]] (1, 5)
PRIORITY:  [0]

 Class: Relevant



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @WhiteHouse: To keep the momentum going in slowing the spread of Coronavirus, the President has extended his nationwide Coronavirus Guid…

['rt', 'keep', 'momentum', 'going', 'slowing', 'spread', 'coronavirus', 'president', 'extended', 'nationwide', 'coronavirus', 'guid…']

 Class: Not Relevant

Tweet: RT @BNODesk: BREAKING: Italy confirms 4,053 new cases and 837 new deaths since yesterday, raising total to 105,792 cases and 12,428 dead ht…

['rt', 'breaking', 'italy', 'confirms', '4,053', 'new', 'cases', '837', 'new', 'deaths', 'since', 'yesterday', 'raising', 'total', '105,792', 'cases', '12,428', 'dead', 'ht…']
[25, 2, 1, 0, 24] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[25 2 1 0 24]] (1, 5)
PRIORITY:  [0]

 Class: Relevant



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @LookNoFurther4: The Pentagon's plan to keep military #Covid_19 statistics secret isn't going well.  The USS Theodore Roosevelt is in tr…

['rt', 'pentagon', "'s", 'plan', 'keep', 'military', 'covid_19', 'statistics', 'secret', "n't", 'going', 'well', 'uss', 'theodore', 'roosevelt', 'tr…']

 Class: Not Relevant

Tweet: RT @funder: .@CNN &amp; @MSNBC should stop airing Trump’s coronavirus press conferences. Raise your hand if you agree. #StopAiringTrump

['rt', '.AT_USER', 'amp', 'stop', 'airing', 'trump', '’', 'coronavirus', 'press', 'conferences', 'raise', 'hand', 'agree', 'stopairingtrump']

 Class: Not Relevant

Tweet: RT @narendramodi: The entire Reliance team has been making effective contributions in the fight against COVID-19. Be it in healthcare or as…

['rt', 'entire', 'reliance', 'team', 'making', 'effective', 'contributions', 'fight', 'covid-19', 'healthcare', 'as…']

 Class: Not Relevant

Tweet: RT @AmoneyResists: Trump held rallies on:
—Jan 9th
—Jan 14th
—Jan 28t

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @Skinnyy_B: The same brand that gave women ovarian cancer w their baby powder?

['rt', 'brand', 'gave', 'women', 'ovarian', 'cancer', 'w', 'baby', 'powder']

 Class: Not Relevant

Tweet: RT @HowToBuildATent: Coronavirus is doing what alcohol does.

It’s bringing people’s true colors out for the world to see. https://t.co/EB7…

['rt', 'coronavirus', 'alcohol', '’', 'bringing', 'people', '’', 'true', 'colors', 'world', 'see']
[24, 8, 3, 2, 21] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[24 8 3 2 21]] (1, 5)
PRIORITY:  [0]

 Class: Relevant



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @4everNeverTrump: @ByronYork @henryolsenEPPC The CDC issued its first warning on Jan 8.

Trump held campaign rallies on Jan 9, Jan 14, J…

['rt', 'cdc', 'issued', 'first', 'warning', 'jan', '8.', 'trump', 'held', 'campaign', 'rallies', 'jan', '9', 'jan', '14', 'j…']
[25, 2, 1, 0, 24] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[25 2 1 0 24]] (1, 5)
PRIORITY:  [0]

 Class: Relevant

Tweet: RT @NorbertElekes: BREAKING: Italy reports 4,053 new cases of coronavirus and 837 new deaths.

Total of 105,792 cases and 12,428 deaths.

['rt', 'breaking', 'italy', 'reports', '4,053', 'new', 'cases', 'coronavirus', '837', 'new', 'deaths', 'total', '105,792', 'cases', '12,428', 'deaths']
[24, 1, 11, 10, 13] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[24 1 11 10 13]] (1, 5)
PRIORITY:  [0]

 Class: Relevant



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @iMac_too: 10 foreign Mullahs discovered in a Mosque of Newasa town in Ahmednagar district, Maharashtra

['rt', '10', 'foreign', 'mullahs', 'discovered', 'mosque', 'newasa', 'town', 'ahmednagar', 'district', 'maharashtra']
[17, 1, 1, 0, 16] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[17 1 1 0 16]] (1, 5)
PRIORITY:  [0]

 Class: Relevant

Tweet: Under the cover of the coronavirus, billionaire looters are stealing America's air, water, and soil https://t.co/4bYoDyHzhu

['cover', 'coronavirus', 'billionaire', 'looters', 'stealing', 'america', "'s", 'air', 'water', 'soil']
[20, 2, 6, 5, 14] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[20 2 6 5 14]] (1, 5)
PRIORITY:  [0]

 Class: Relevant



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @thedailybeast: BREAKING: U.S. Secretary of State Mike Pompeo reportedly confirmed on Tuesday that a state department official had died…

['rt', 'breaking', 'u.s.', 'secretary', 'state', 'mike', 'pompeo', 'reportedly', 'confirmed', 'tuesday', 'state', 'department', 'official', 'died…']
[21, 3, 1, 0, 20] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[21 3 1 0 20]] (1, 5)
PRIORITY:  [0]

 Class: Relevant



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @sajajohnson: The NHS is more than just doctors and nurses. I spoke to five people in vital roles whose voices haven't been heard much y…

['rt', 'nhs', 'doctors', 'nurses', 'spoke', 'five', 'people', 'vital', 'roles', 'whose', 'voices', "n't", 'heard', 'much', 'y…']

 Class: Not Relevant

Tweet: Play stupid games win stupid prizes

['play', 'stupid', 'games', 'win', 'stupid', 'prizes']

 Class: Not Relevant

Tweet: #COVID19 | Important questions and their answers! #coronavirus https://t.co/l9lxypuY4r

['covid19', 'important', 'questions', 'answers', 'coronavirus']
[10, 1, 9, 8, 1] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[10 1 9 8 1]] (1, 5)
PRIORITY:  [0]

 Class: Relevant

Tweet: RT @AdityaRajKaul: Delhi Police had already issued orders to the organisers of #TablighiJamat to vacate premises to stop spread of #CoronaV…

['rt', 'delhi', 'police', 'already', 'issued', 'orders', 'organisers', 'tablighijamat', 'vacate', 'premises', 'stop', 

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: BBC News - Coronavirus: Virus prompts recruitment drive for fruit pickers https://t.co/WNLzS8H4N8

['bbc', 'news', 'coronavirus', 'virus', 'prompts', 'recruitment', 'drive', 'fruit', 'pickers']
[13, 2, 4, 3, 9] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[13 2 4 3 9]] (1, 5)
PRIORITY:  [0]

 Class: Relevant

Tweet: RT @MotherJones: As the nation worries about coronavirus, the Trump administration is rolling back environmental rules. https://t.co/5205Pj…

['rt', 'nation', 'worries', 'coronavirus', 'trump', 'administration', 'rolling', 'back', 'environmental', 'rules']

 Class: Not Relevant



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @mmpadellan: OK, who had the My Pillow guy appearing in a "coronavirus briefing" on their crazy BINGO card?

No you didn't. Stop.
This i…

['rt', 'ok', 'pillow', 'guy', 'appearing', '``', 'coronavirus', 'briefing', "''", 'crazy', 'bingo', 'card', "n't", 'stop', 'i…']

 Class: Not Relevant

Tweet: RT @corbinball: How the Event Industry Is Assisting Hospitals and Medical Workers Around the Country Amid the Coronavirus Outbreak #eventpr…

['rt', 'event', 'industry', 'assisting', 'hospitals', 'medical', 'workers', 'around', 'country', 'amid', 'coronavirus', 'outbreak', 'eventpr…']
[20, 3, 18, 17, 2] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[20 3 18 17 2]] (1, 5)
PRIORITY:  [0]

 Class: Relevant



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @BNODesk: BREAKING: Italy confirms 4,053 new cases and 837 new deaths since yesterday, raising total to 105,792 cases and 12,428 dead ht…

['rt', 'breaking', 'italy', 'confirms', '4,053', 'new', 'cases', '837', 'new', 'deaths', 'since', 'yesterday', 'raising', 'total', '105,792', 'cases', '12,428', 'dead', 'ht…']
[25, 2, 1, 0, 24] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[25 2 1 0 24]] (1, 5)
PRIORITY:  [0]

 Class: Relevant

Tweet: RT @21WIRE: Putting things into perspective... 

Why not have a #lockdown for the seasonal flu next winter? 
#coronavirus #COVID19 https://…

['rt', 'putting', 'things', 'perspective', '...', 'lockdown', 'seasonal', 'flu', 'next', 'winter', 'coronavirus', 'covid19']
[22, 2, 20, 19, 2] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[22 2 20 19 2]] (1, 5)
PRIORITY:  [0]

 Class: Relevant



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @morningmoneyben: Never been more jealous of a curve in my life. Man they nailed it. 
Via Time. 
https://t.co/sktEp8booM https://t.co/so…

['rt', 'never', 'jealous', 'curve', 'life', 'man', 'nailed', 'via', 'time']

 Class: Not Relevant

Tweet: RT @21WIRE: Putting things into perspective... 

Why not have a #lockdown for the seasonal flu next winter? 
#coronavirus #COVID19 https://…

['rt', 'putting', 'things', 'perspective', '...', 'lockdown', 'seasonal', 'flu', 'next', 'winter', 'coronavirus', 'covid19']
[22, 2, 20, 19, 2] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[22 2 20 19 2]] (1, 5)
PRIORITY:  [0]

 Class: Relevant



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: Couldn’t agree more.

['’', 'agree']

 Class: Not Relevant

Tweet: @realDonaldTrump Trump tanks mileage standards and guts climate change while you are concentrated on coronavirus. D… https://t.co/0cjTrFzi4Z

['trump', 'tanks', 'mileage', 'standards', 'guts', 'climate', 'change', 'concentrated', 'coronavirus', 'd…']
[18, 3, 15, 14, 3] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[18 3 15 14 3]] (1, 5)
PRIORITY:  [0]

 Class: Relevant



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @NorbertElekes: NEW: Head of Moscow's main coronavirus hospital tested positive for coronavirus.

He met with President Putin last week.…

['rt', 'new', 'head', 'moscow', "'s", 'main', 'coronavirus', 'hospital', 'tested', 'positive', 'coronavirus', 'met', 'president', 'putin', 'last', 'week.…']
[24, 3, 15, 14, 9] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[24 3 15 14 9]] (1, 5)
PRIORITY:  [1]

 Class: Relevant

Tweet: RT @CNNPolitics: President Trump's coronavirus briefings lack a crucial element: Empathy | Analysis https://t.co/DzMs47qRz5 https://t.co/kH…

['rt', 'president', 'trump', "'s", 'coronavirus', 'briefings', 'lack', 'crucial', 'element', 'empathy', 'analysis']
[17, 1, 6, 5, 11] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[17 1 6 5 11]] (1, 5)
PRIORITY:  [0]

 Class: Relevant



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @KellyMalmberg: Thanks to Coronavirus my youngest kid is currently unemployed and is worried about paying her bills, but I can sleep at…

['rt', 'thanks', 'coronavirus', 'youngest', 'kid', 'currently', 'unemployed', 'worried', 'paying', 'bills', 'sleep', 'at…']

 Class: Not Relevant

Tweet: RT @DHSCgovuk: UPDATE on coronavirus (#COVID19) testing in the UK:

As of 9am 31 March, a total of 143,186 people have been tested of which…

['rt', 'update', 'coronavirus', 'covid19', 'testing', 'uk', '9am', '31', 'march', 'total', '143,186', 'people', 'tested', 'which…']
[29, 3, 5, 4, 24] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[29 3 5 4 24]] (1, 5)
PRIORITY:  [0]

 Class: Relevant



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: Highlight: “We know exactly what we need to do step by step,” J&amp;J Chief Scientific Officer Dr. Paul Stoffels says a… https://t.co/15xj1QQlBe

['highlight', '“', 'know', 'exactly', 'need', 'step', 'step', '”', 'j', 'amp', 'j', 'chief', 'scientific', 'officer', 'dr.', 'paul', 'stoffels', 'says', 'a…']

 Class: Not Relevant

Tweet: RT @Nigensei: Empty hotels all over the city of Las Vegas and they’re putting the homeless in a fucking parking lot.

['rt', 'empty', 'hotels', 'city', 'las', 'vegas', '’', 'putting', 'homeless', 'fucking', 'parking', 'lot']

 Class: Not Relevant

Tweet: RT @leilaibi: Quarantine for ever more..

['rt', 'quarantine', 'ever', 'more..']

 Class: Not Relevant

Tweet: Uhh what?

['uhh']

 Class: Not Relevant

Tweet: RT @adnan73_siddiqi: @salma_anjum1 Wow!!! Where can I find a J&amp;K Bank branch here in Karachi, I wish to bequeath every penny to fight Coron…

['rt', 'wow', 'find', 'j', 'amp', 'k', 'bank', 'branch', 'karachi', 'wish', 'bequeath', 'every', 

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @SenWarren: Coronavirus doesn’t discriminate, but racial disparities in our health care system may mean Black and Brown families aren't…

['rt', 'coronavirus', '’', 'discriminate', 'racial', 'disparities', 'health', 'care', 'system', 'may', 'mean', 'black', 'brown', 'families', "aren't…"]
[23, 2, 3, 2, 20] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[23 2 3 2 20]] (1, 5)
PRIORITY:  [0]

 Class: Relevant

Tweet: RT @jayasax: Reminder that Whole Foods workers are walking out today, so don't cross that picket line https://t.co/iBpLAtTCMX

['rt', 'reminder', 'whole', 'foods', 'workers', 'walking', 'today', "n't", 'cross', 'picket', 'line']
[20, 4, 1, 0, 19] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[20 4 1 0 19]] (1, 5)
PRIORITY:  [0]

 Class: Relevant



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @b_fung: Amazon has fired the warehouse worker who organized a walkout yesterday to protest the level of coronavirus protections at the…

['rt', 'amazon', 'fired', 'warehouse', 'worker', 'organized', 'walkout', 'yesterday', 'protest', 'level', 'coronavirus', 'protections', 'the…']
[22, 4, 19, 18, 3] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[22 4 19 18 3]] (1, 5)
PRIORITY:  [0]

 Class: Relevant

Tweet: RT @HRHBethany: @DonaldJTrumpJr @nypost Remember. 

The CDC issued its first warning on Jan 8.

Trump held rallies on Jan 9, Jan 14, Jan 28…

['rt', 'remember', 'cdc', 'issued', 'first', 'warning', 'jan', '8.', 'trump', 'held', 'rallies', 'jan', '9', 'jan', '14', 'jan', '28…']
[27, 2, 1, 0, 26] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[27 2 1 0 26]] (1, 5)
PRIORITY:  [0]

 Class: Relevant



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @Reuters: From rate cuts to quantitative easing: Here's a look at the Federal Reserve's actions during the coronavirus outbreak: https:/…

['rt', 'rate', 'cuts', 'quantitative', 'easing', "'s", 'look', 'federal', 'reserve', "'s", 'actions', 'coronavirus', 'outbreak', 'https', '/…']
[27, 2, 22, 21, 5] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[27 2 22 21 5]] (1, 5)
PRIORITY:  [0]

 Class: Relevant

Tweet: @paddypower I think that your adverts, shown during #TheWalkingDeadUK , are unfortunately apt during this #COVID19… https://t.co/yq5WwREnkI

['think', 'adverts', 'shown', 'thewalkingdeaduk', 'unfortunately', 'apt', 'covid19…']
[18, 3, 1, 0, 17] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[18 3 1 0 17]] (1, 5)
PRIORITY:  [0]

 Class: Relevant



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @marcorubio: Here is todays reminder of how some in the media continue to use fake numbers from #China’s Communist Party to argue not ju…

['rt', 'todays', 'reminder', 'media', 'continue', 'use', 'fake', 'numbers', 'china', '’', 'communist', 'party', 'argue', 'ju…']
[26, 5, 1, 0, 25] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[26 5 1 0 25]] (1, 5)
PRIORITY:  [0]

 Class: Relevant

Tweet: RT @thehill: JUST IN: McConnell says Dem impeachment push distracted government from coronavirus threat https://t.co/vAwWRZ5UAY https://t.c…

['rt', 'mcconnell', 'says', 'dem', 'impeachment', 'push', 'distracted', 'government', 'coronavirus', 'threat']
[17, 3, 14, 13, 3] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[17 3 14 13 3]] (1, 5)
PRIORITY:  [0]

 Class: Relevant



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @TIME: New York’s Empire State Building was lit up like an ambulance Monday night in honor of first responders and medical professionals…

['rt', 'new', 'york', '’', 'empire', 'state', 'building', 'lit', 'like', 'ambulance', 'monday', 'night', 'honor', 'first', 'responders', 'medical', 'professionals…']

 Class: Not Relevant

Tweet: RT @RobUlven: @ishakethethrone @arch1com @Presidementia @sisneruza @MaryScull @paulkrugman @RiganoESQ The whole story - Dr. Andrew G. Weber…

['rt', 'whole', 'story', 'dr.', 'andrew', 'g.', 'weber…']

 Class: Not Relevant

Tweet: RT @TheVoiceNews: Why were black NHS staff whitewashed out of Clap For Our Carers? | @dotunadebayo https://t.co/rCx1cscbME

['rt', 'black', 'nhs', 'staff', 'whitewashed', 'clap', 'carers']

 Class: Not Relevant

Tweet: RT @AndrewYang: That’s not cool. Be nice to others and appreciate each other.  🙏

['rt', '’', 'cool', 'nice', 'others', 'appreciate', '🙏']

 Class: Not Relevant

Tweet: RT @TIME: New York’s Empire State Bui

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: Using AI to fight Coronavirus,  https://t.co/QXx2ZiwzaK  artificial intelligence https://t.co/X2bsQT24bD

['using', 'ai', 'fight', 'coronavirus', 'artificial', 'intelligence']

 Class: Not Relevant

Tweet: The coronavirus crisis has exposed the ugly truth about celebrity culture and capitalism | Arwa Mahdawi https://t.co/Bn8vpkWfMK

['coronavirus', 'crisis', 'exposed', 'ugly', 'truth', 'celebrity', 'culture', 'capitalism', 'arwa', 'mahdawi']
[17, 2, 2, 1, 15] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[17 2 2 1 15]] (1, 5)
PRIORITY:  [0]

 Class: Relevant



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @KamalaHarris: An Asian American father and his 2-year-old and 6-year-old were stabbed because the perpetrator thought they were Chinese…

['rt', 'asian', 'american', 'father', '2-year-old', '6-year-old', 'stabbed', 'perpetrator', 'thought', 'chinese…']

 Class: Not Relevant

Tweet: Nervous Nancy the raging alcoholic broken woman Pelosis daily lie ..

['nervous', 'nancy', 'raging', 'alcoholic', 'broken', 'woman', 'pelosis', 'daily', 'lie', '..']

 Class: Not Relevant

Tweet: RT @renoomokri: Retweet this if you believe China should pay reparations to every country that has suffered human or economic loss as a res…

['rt', 'retweet', 'believe', 'china', 'pay', 'reparations', 'every', 'country', 'suffered', 'human', 'economic', 'loss', 'res…']

 Class: Not Relevant

Tweet: RT @yagiirlalyssaaa: Please watch this #coronavirus a remedy that can probably help https://t.co/qESuYCOZym

['rt', 'please', 'watch', 'coronavirus', 'remedy', 'probably', 'help']

 Class: Not Relevant

Tweet:

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @Skinnyy_B: The same brand that gave women ovarian cancer w their baby powder?

['rt', 'brand', 'gave', 'women', 'ovarian', 'cancer', 'w', 'baby', 'powder']

 Class: Not Relevant

Tweet: RT @PaulHenriCadier: Coronavirus testing delayed after kits found to be contaminated by Covid-19 https://t.co/DR6FNFpCJa

['rt', 'coronavirus', 'testing', 'delayed', 'kits', 'found', 'contaminated', 'covid-19']
[14, 5, 3, 2, 11] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[14 5 3 2 11]] (1, 5)
PRIORITY:  [0]

 Class: Relevant



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @etiennelefleur: Garden centres giving away plants that can't be sold because of #coronavirus is great idea, but growers, wholesalers &amp;…

['rt', 'garden', 'centres', 'giving', 'away', 'plants', 'ca', "n't", 'sold', 'coronavirus', 'great', 'idea', 'growers', 'wholesalers', 'amp', '…']

 Class: Not Relevant

Tweet: RT @rgrunbaum: Inside the ‘incredibly challenging’ effort by GM and Ventec to make more ventilators for coronavirus fight, by @GeoffBakerTI…

['rt', 'inside', '‘', 'incredibly', 'challenging', '’', 'effort', 'gm', 'ventec', 'make', 'ventilators', 'coronavirus', 'fight']

 Class: Not Relevant

Tweet: RT @EdHull8: Trump accused of using #coronavirus briefing as corporate advertising spot as USA death toll rises beyond 3,500. #PresidentAme…

['rt', 'trump', 'accused', 'using', 'coronavirus', 'briefing', 'corporate', 'advertising', 'spot', 'usa', 'death', 'toll', 'rises', 'beyond', '3,500.', 'presidentame…']
[20, 3, 7, 6, 13] ['no_of_words', 'no_of_verbs', 'pos_query

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @RealBisi: Sharing stuff like this is wild because we do have people dumb enough to believe it

['rt', 'sharing', 'stuff', 'like', 'wild', 'people', 'dumb', 'enough', 'believe']

 Class: Not Relevant

Tweet: RT @MataPresident: @foxnation host: "Con men prey on fear during coronavirus crisis; The most vulnerable among us are prime targets for cri…

['rt', 'host', '``', 'con', 'men', 'prey', 'fear', 'coronavirus', 'crisis', 'vulnerable', 'among', 'us', 'prime', 'targets', 'cri…']

 Class: Not Relevant

Tweet: RT @SWSandy_: Assistant Commissioner Neil Basu demanded that officers maintain the British tradition of 'policing by consent' as he emphasi…

['rt', 'assistant', 'commissioner', 'neil', 'basu', 'demanded', 'officers', 'maintain', 'british', 'tradition', "'policing", 'consent', 'emphasi…']
[21, 4, 1, 0, 20] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[21 4 1 0 20]] (1, 5)
PRIORITY:  [0]

 Class: Relevant

Tweet: RT @CaslerNoel: It’s always

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @zellieimani: Once the government called this the “War on coronavirus”, I just knew it wasn’t going to end anytime soon.

['rt', 'government', 'called', '“', 'war', 'coronavirus', '”', 'knew', '’', 'going', 'end', 'anytime', 'soon']
[24, 5, 11, 10, 13] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[24 5 11 10 13]] (1, 5)
PRIORITY:  [0]

 Class: Relevant

Tweet: RT @anadoluagency: #BREAKING Death toll in Turkey from coronavirus surges to 214 after 46 more people die on Tuesday

['rt', 'breaking', 'death', 'toll', 'turkey', 'coronavirus', 'surges', '214', '46', 'people', 'die', 'tuesday']
[19, 2, 9, 8, 10] ['no_of_words', 'no_of_verbs', 'pos_query_word', 'word_before', 'word_after']
[[19 2 9 8 10]] (1, 5)
PRIORITY:  [0]

 Class: Relevant



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


Tweet: RT @StevenBeschloss: Every time I see Trump now, I think of the coronavirus patients, in pain, gasping for air. I think how many will lose…

['rt', 'every', 'time', 'see', 'trump', 'think', 'coronavirus', 'patients', 'pain', 'gasping', 'air', 'think', 'many', 'lose…']

 Class: Not Relevant

Tweet: great little article, thanks

['great', 'little', 'article', 'thanks']

 Class: Not Relevant

Tweet: RT @cllrRLangton: Self-isolating and in need of food? You can now purchase a food parcel from Nottingham City Council, to be delivered to y…

['rt', 'self-isolating', 'need', 'food', 'purchase', 'food', 'parcel', 'nottingham', 'city', 'council', 'delivered', 'y…']

 Class: Not Relevant

Tweet: RT @RealKyleMorris: Twitter Forces @IngrahamAngle to Delete Post on Chloroquine Helping Coronavirus Patients https://t.co/ztpX0LIPIV

['rt', 'twitter', 'forces', 'delete', 'post', 'chloroquine', 'helping', 'coronavirus', 'patients']
[14, 3, 12, 11, 2] ['no_of_words', 'no_of_verbs', 'pos_query_word

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


KeyboardInterrupt: 